from setuptools import setup

setup(
    name='id_phonenumbers',
    packages=['id_phonenumbers'],
    version='0.4.0',
    description='Indonesian Phonenumbers Parser',
    license='MIT',
    author='Steven',
    author_email='stvn.bu@gmail.com',
    url='https://github.com/SeiryuZ/id_phonenumbers',
    download_url='https://github.com/SeiryuZ/id_phonenumbers/tarball/0.2.0',
    keywords=['phonenumbers', 'Indonesia'],
    install_requires=['phonenumberslite'],
    classifiers=[
        'Development Status :: 3 - Alpha',
        'Intended Audience :: Developers',
        'Programming Language :: Python',
        'Programming Language :: Python :: 2',
        'Programming Language :: Python :: 2.7',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.3',
        'Programming Language :: Python :: 3.4',
        'Programming Language :: Python :: 3.5',
        'Programming Language :: Python :: 3.6',
        'License :: OSI Approved :: MIT License',
        'Operating System :: OS Independent',
        'Topic :: Internet :: WWW/HTTP',
        'Topic :: Software Development :: Libraries :: Python Modules',
    ],
)
